version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8081"
  webserver:
    image: nginx:latest
    ports:
      - 8080:8080
      - 4443:4443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
      - ./key.pem:/root/ssl/
      - ./cert.pem:/root/ssl/
    depends_on:
      - web