version: '3'
services:
  web:
      build: .
      ports:
        - "81:81"
     
  webserver:
    image: nginx:latest
    ports:
      - 8081:8080
      - 4443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    depends_on:
      - web